[[redirects]]
  from = "/api/get-clerk-key"
  to = "/.netlify/functions/get-clerk-key"
  status = 200

[[redirects]]
  from = "/api/get-gemini-key"
  to = "/.netlify/functions/get-gemini-key"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
